#!/usr/bin/env python3
"""Check every relative link in the repository's Markdown.

This repo is mostly documentation, and it is documentation that points at itself:
four edition directories, each with its own README, docs, plugin skill and
reference files, all cross-linking to the root and to each other. Moving or
renaming a file breaks those links silently -- nothing fails, the link just stops
resolving, and the next reader finds a 404 instead of the contract they were sent
to read.

Only relative links are checked. External URLs are left to a human: this must
stay offline and deterministic so it can sit inside the canonical gate.

    python tools/check_links.py
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent.parent

LINK_PATTERN = re.compile(r"(?<!!)\[[^\]]*\]\(([^)]+)\)")
IMAGE_PATTERN = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
HTML_SRC_PATTERN = re.compile(r"""(?is)<img[^>]+src=["']([^"']+)["']""")

SKIP_PREFIXES = ("http://", "https://", "mailto:", "tel:", "#", "$")

# Generated by the scheduled checks into the workspace, never committed.
SKIP_NAMES = {
    "upstream-review-report.md",
    "dependency-freshness-report.md",
}


def iter_documents() -> list[Path]:
    """Every tracked Markdown file.

    `git ls-files` rather than a glob: it inherits `.gitignore`, so a local
    scratch file or an untracked report can never turn the gate red.
    """
    result = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "*.md"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode != 0:
        return sorted(
            path for path in ROOT.rglob("*.md") if ".git" not in path.parts
        )
    return sorted(
        ROOT / line
        for line in result.stdout.splitlines()
        if line and Path(line).name not in SKIP_NAMES
    )


def missing_target(path: Path, target: str) -> str | None:
    """Return a description of the broken link, or None when it resolves."""
    target = target.strip().strip("<>")
    if not target or target.startswith(SKIP_PREFIXES):
        return None
    # A link may carry a title: [text](./file.md "Title").
    file_part = unquote(target.split()[0].split("#", 1)[0])
    if not file_part:
        return None
    resolved = (path.parent / file_part).resolve()
    if resolved.exists():
        return None
    try:
        shown = resolved.relative_to(ROOT)
    except ValueError:
        shown = resolved
    return f"{target} -> missing {shown}"


def check_document(path: Path) -> list[str]:
    problems: list[str] = []
    text = path.read_text(encoding="utf-8")
    for pattern in (LINK_PATTERN, IMAGE_PATTERN, HTML_SRC_PATTERN):
        for match in pattern.finditer(text):
            problem = missing_target(path, match.group(1))
            if problem:
                problems.append(problem)
    return problems


def main() -> int:
    documents = iter_documents()
    if not documents:
        print("FAIL: no tracked Markdown files were found")
        return 1

    failures = 0
    for path in documents:
        relative = path.relative_to(ROOT)
        problems = check_document(path)
        if problems:
            failures += 1
            for problem in problems:
                print(f"FAIL {relative}: {problem}")
        else:
            print(f"OK   {relative}")

    print(f"\n{len(documents)} Markdown files checked, {failures} with broken links.")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
